import {
  ChevronRight,
  Facebook,
  Instagram,
  Menu,
  Twitter,
  X,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useRef, useState } from "react";

// ─── Types ────────────────────────────────────────────────────────────────────
interface BlogPost {
  id: number;
  title: string;
  date: string;
  category: string;
  excerpt: string;
  fullContent: string[];
  imageUrl: string;
}

// ─── Static Blog Data ─────────────────────────────────────────────────────────
const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: "The Power of Vitamin C Serums: Brighten Your Skin Naturally",
    date: "March 18, 2026",
    category: "Ingredient Spotlight",
    excerpt:
      "Vitamin C is one of the most researched skin actives in the beauty world. Discover how this powerhouse antioxidant fades dark spots, evens skin tone, and defends against daily environmental damage.",
    imageUrl: "/assets/generated/skinblog-post-vitaminc.dim_800x500.jpg",
    fullContent: [
      "Vitamin C — ascorbic acid in its purest form — has earned its reputation as skincare's most reliable brightening ingredient. Backed by decades of clinical research, it consistently delivers visible improvements in skin radiance, tone, and texture when used correctly and consistently.",
      "At the biological level, vitamin C inhibits the enzyme tyrosinase, which is responsible for producing melanin — the pigment that creates dark spots and hyperpigmentation. By slowing melanin synthesis, vitamin C gradually fades existing discolouration while preventing new spots from forming. This makes it particularly effective for post-acne marks, sun damage, and melasma.",
      "Beyond brightening, vitamin C is one of nature's most potent antioxidants. Free radicals — generated by UV exposure, pollution, and stress — oxidise skin cells and degrade collagen. Vitamin C donates electrons to neutralise these unstable molecules before they cause lasting damage, effectively acting as a molecular shield around your skin cells.",
      "One of vitamin C's most exciting properties is its ability to stimulate collagen synthesis. Collagen is the structural protein responsible for skin's firmness and elasticity, and its production declines steadily from our mid-twenties. By upregulating collagen gene expression, regular vitamin C use helps maintain skin density and reduces the depth of fine lines over time.",
      "Not all vitamin C serums are created equal. L-ascorbic acid is the most bioavailable form, but it's notoriously unstable — it oxidises rapidly when exposed to light and air, turning orange and losing potency. Stabilised derivatives such as ascorbyl glucoside or sodium ascorbyl phosphate are gentler and longer-lasting, making them better options for sensitive skin.",
      "For best results, apply your vitamin C serum in the morning on clean skin, before moisturiser and SPF. The antioxidant protection it provides pairs synergistically with sunscreen, amplifying your defence against UV-induced damage. Store it in a cool, dark drawer and replace it every three months for optimal potency.",
    ],
  },
  {
    id: 2,
    title: "How to Layer Your Serums: A Step-by-Step Guide",
    date: "March 10, 2026",
    category: "Tutorial",
    excerpt:
      "Using multiple serums is one of the most powerful ways to target several skin concerns at once — but only if you layer them correctly. Here's the definitive guide to serum sequencing for every skin type.",
    imageUrl: "/assets/generated/skinblog-post-layering.dim_800x500.jpg",
    fullContent: [
      "Serums are the concentrated workhorses of any skincare routine — small in volume but enormous in impact. When you want to address multiple concerns simultaneously, the temptation is to reach for every serum you own. But layering without a strategy can lead to reduced efficacy, irritation, or product pilling on the skin.",
      "The golden rule of serum layering is simple: thinnest to thickest. Water-based serums have the lowest molecular weight and need to be applied first to penetrate the deepest layers of the skin. Heavier, oil-based serums are applied later, as they create a partial seal that would block lighter formulas from absorbing if applied first.",
      "pH is the second factor to consider. Vitamin C serums and exfoliating acids (AHAs and BHAs) work optimally at a low pH — around 3 to 4. Niacinamide and peptides work at a neutral to slightly acidic pH. To avoid potential interactions and ensure each active functions correctly, apply low-pH products first and allow them to fully absorb for two to three minutes before the next layer.",
      "A morning layering sequence might look like this: cleanser → toner → vitamin C serum → hyaluronic acid serum → moisturiser → SPF. The vitamin C provides antioxidant protection for the day, while hyaluronic acid draws moisture into skin that has just been cleansed. Both are water-based, so they sit comfortably on top of each other.",
      "Evening layering allows for richer, more reparative actives. After cleansing and toning, apply any exfoliating acid serum first if using one, followed by a retinol or retinoid serum (not on the same night as exfoliants if you're sensitive), then a peptide or niacinamide serum, and finally a facial oil or occlusive moisturiser to lock everything in while you sleep.",
      "One important caveat: do not use retinol and vitamin C in the same routine. Both are potent actives that can cause irritation when combined, and they work best in different conditions — vitamin C in the morning (pairs with SPF), retinol at night (no sunlight required). Give each active the optimal environment to work, and your skin will reward you.",
    ],
  },
  {
    id: 3,
    title: "Hyaluronic Acid: The Ultimate Hydration Ingredient",
    date: "February 28, 2026",
    category: "Ingredient Deep Dive",
    excerpt:
      "Hyaluronic acid can hold up to 1,000 times its own weight in water, making it the ultimate hydrating ingredient. But there's a science to using it correctly — and most people are applying it wrong.",
    imageUrl: "/assets/generated/skinblog-post-hyaluronic.dim_800x500.jpg",
    fullContent: [
      "Hyaluronic acid (HA) is a glycosaminoglycan — a naturally occurring polysaccharide — found in the skin, joints, and connective tissue. It's the body's own moisture-binding molecule, capable of holding up to 1,000 times its weight in water. As we age, our natural HA levels decline, contributing to the loss of skin plumpness and the appearance of fine lines.",
      "What makes HA unique in skincare is its molecular flexibility. Skincare brands use hyaluronic acid in various molecular weights, each with a different function. High molecular weight HA sits on the surface of the skin, forming a film that prevents transepidermal water loss and gives an immediate plumping effect. Low molecular weight HA penetrates more deeply, hydrating from within.",
      "The best HA serums use multiple molecular weights simultaneously — sometimes called 'multi-weight hyaluronic acid.' This layered approach addresses hydration at every depth of the skin, delivering both immediate surface softness and longer-term structural hydration. Look for serums that list sodium hyaluronate (the salt form, more stable) or hydrolysed hyaluronic acid alongside standard HA.",
      "Here's the common mistake: applying hyaluronic acid serum to completely dry skin. HA works as a humectant — it draws moisture from its environment. If there's no moisture available, it will pull water from the deeper layers of your skin, paradoxically causing dehydration. Always apply HA to slightly damp skin, either just after cleansing or after misting your face, then lock it in immediately with a moisturiser.",
      "HA works beautifully alongside almost every other active ingredient, making it one of the safest and most versatile additions to any routine. It buffers the potential irritation of retinol and acids, boosts the skin's resilience to environmental stressors, and supports the barrier function that keeps skin healthy and calm.",
      "For combination and oily skin types, a lightweight HA gel serum used twice daily can replace heavier moisturisers while still maintaining optimal hydration. For dry and mature skin, layering HA under a richer cream multiplies the hydration effect, and using a facial mist over the top seals everything in for long-lasting comfort.",
    ],
  },
  {
    id: 4,
    title: "Natural Oils vs. Serums: Which Is Right for You?",
    date: "February 15, 2026",
    category: "Skincare Guide",
    excerpt:
      "Facial oils and serums both promise radiant skin, but they work in fundamentally different ways. Understanding the difference helps you choose — or combine — them for results tailored to your unique skin needs.",
    imageUrl: "/assets/generated/skinblog-post-naturaloils.dim_800x500.jpg",
    fullContent: [
      "Walk into any natural beauty store and you'll find shelves lined with both serums and facial oils, each promising luminous, healthy skin. They're often marketed interchangeably, but they perform very different roles in the skin's ecosystem — and knowing the difference is key to building a routine that actually works.",
      "Serums are water-based concentrates formulated with active ingredients — vitamins, peptides, exfoliants, antioxidants — designed to penetrate the deeper layers of the skin and deliver targeted results. Their light, watery texture allows them to absorb quickly and work at a cellular level. They're the power tools of skincare: precise, potent, and purpose-built.",
      "Facial oils, by contrast, are lipid-based. They don't penetrate the skin in the same way as water-based actives; instead, they primarily work on the surface and in the upper layers of the skin. Their function is to reinforce the skin barrier, prevent transepidermal water loss, and soften the outer layer. Many natural oils also contain antioxidants and fatty acids that nourish the skin over time.",
      "The best oils for dry or mature skin tend to be rich in oleic acid — think rosehip, argan, and marula — which mimic the skin's natural lipids and absorb beautifully without leaving a heavy residue. Oily and acne-prone skin often responds better to oils high in linoleic acid, such as hemp seed or rosehip, which are lighter and can help regulate sebum production.",
      "For most people, the ideal routine combines both. Apply your water-based serum first — vitamin C, hyaluronic acid, or a targeted treatment — then follow with one to two drops of facial oil to seal everything in. This is especially effective in an evening routine, where the oil acts as a finishing step to lock in the benefits of everything applied beneath it.",
      "There are some situations where oils should be avoided or used carefully. If you're using strong exfoliating acids in your routine, applying oil directly after may reduce their efficacy. And if you have active breakouts, certain oils (particularly comedogenic ones like coconut) can worsen congestion. The key is to choose your oil based on your skin type and always patch test new products.",
    ],
  },
  {
    id: 5,
    title: "Building a Minimal Skincare Routine with Serums",
    date: "February 3, 2026",
    category: "Minimalist Living",
    excerpt:
      "More products doesn't mean better skin. A focused three-step serum routine can outperform a ten-step regimen when every product earns its place. Here's how to build a minimal routine that actually delivers.",
    imageUrl: "/assets/generated/skinblog-post-minimal.dim_800x500.jpg",
    fullContent: [
      "Skincare minimalism isn't about cutting corners — it's about cutting noise. The beauty industry profits from complexity, convincing us that more products mean more results. But the evidence points in the opposite direction: a small number of well-chosen, consistently used products consistently outperforms a cluttered regime of overlapping actives.",
      "The foundation of a minimal serum routine is understanding what your skin actually needs versus what marketing tells you it needs. Most healthy adult skin requires three things: cleansing, hydration, and sun protection. For targeted concerns, one or two focused actives are almost always sufficient.",
      "A minimal morning routine looks like this: gentle cleanser → vitamin C serum → lightweight moisturiser → SPF. That's it. The vitamin C addresses brightening, antioxidant protection, and collagen support simultaneously. The moisturiser maintains hydration. The SPF prevents further damage. Four steps, maximum benefit.",
      "For evenings, swap the vitamin C for a retinol or bakuchiol serum (depending on your sensitivity level), and follow with a slightly richer moisturiser or a few drops of facial oil. Two distinct routines — morning focused on protection, evening focused on repair — each with minimal, non-overlapping steps.",
      "The key to making a minimal routine work is choosing multi-tasking serums. A good vitamin C serum doesn't just brighten — it also provides antioxidant protection and supports collagen synthesis. A well-formulated niacinamide serum addresses pores, redness, and hydration in one product. Choosing serums with multiple verified benefits reduces the need for product layering.",
      "Give your minimal routine at least eight weeks before evaluating results. The desire to add products often stems from impatience rather than genuine need. Document your skin with photographs in consistent lighting every two weeks. You'll likely find that your stripped-back routine is performing better than you realise — and your skin will be calmer and more balanced for it.",
    ],
  },
  {
    id: 6,
    title: "Retinol Alternatives: Natural Ingredients for Anti-Aging",
    date: "January 22, 2026",
    category: "Natural Alternatives",
    excerpt:
      "Retinol delivers results, but it's not for everyone. Sensitivity, pregnancy, and reactive skin types need gentler options. Here are the most effective plant-based alternatives that actually work.",
    imageUrl: "/assets/generated/skinblog-post-retinol-alt.dim_800x500.jpg",
    fullContent: [
      "Retinol — a derivative of vitamin A — is widely considered the gold standard for anti-ageing. Clinical trials consistently show it reduces the appearance of fine lines, improves skin texture, and encourages healthy cell turnover. But with these benefits come significant downsides: irritation, dryness, photosensitivity, and unsuitability during pregnancy.",
      "For those who can't tolerate retinol or choose to avoid it, the good news is that plant science has produced several compelling alternatives. These natural retinol alternatives work through similar biological pathways — stimulating collagen production and cell renewal — but without the irritation profile that makes retinol difficult for many people.",
      "Bakuchiol is the most well-studied natural retinol alternative. Derived from the seeds of the Psoralea corylifolia plant, bakuchiol has been shown in clinical trials to match retinol's effect on fine lines and skin firmness, without causing redness, peeling, or photosensitivity. It's also safe during pregnancy — a significant advantage. It can be used morning and evening, making it a versatile addition to any routine.",
      "Rosehip oil contains a naturally occurring form of trans-retinoic acid called tretinoin, which is the active metabolite of retinol. While present in lower concentrations than synthetic formulations, it still offers meaningful support for cell turnover and collagen synthesis over time. Cold-pressed rosehip oil also delivers essential fatty acids, vitamin C, and vitamin E alongside its vitamin A benefits.",
      "Sea buckthorn oil is another vitamin A-rich botanical worth knowing. Intensely orange due to its high carotenoid content, it contains beta-carotene (a vitamin A precursor) alongside omega-7 fatty acids, which are rare in plant sources and exceptionally supportive of skin barrier function and mucous membrane health. Use it sparingly blended with another carrier oil, as the colour can temporarily stain lighter skin tones.",
      "For those easing into vitamin A use of any kind, start with bakuchiol twice weekly and build to daily use over four to six weeks. Patience is essential — natural alternatives work more gently than synthetic retinol, and results develop over several months rather than weeks. But for long-term skin health, a gentle, consistent approach almost always wins over aggressive treatments that compromise the barrier.",
    ],
  },
];

// ─── Active nav sections ───────────────────────────────────────────────────────
const NAV_LINKS = ["HOME", "POSTS", "ABOUT", "CONTACT"] as const;

// ─── App Component ─────────────────────────────────────────────────────────────
export default function App() {
  const year = new Date().getFullYear();
  const hostname = encodeURIComponent(window.location.hostname);

  const [activeNav, setActiveNav] = useState<string>("HOME");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);
  const modalRef = useRef<HTMLDivElement>(null);

  // Close modal on Escape
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") setSelectedPost(null);
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  // Prevent body scroll when modal open
  useEffect(() => {
    if (selectedPost) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [selectedPost]);

  // Track active section via IntersectionObserver
  useEffect(() => {
    const sections = ["home", "posts", "about", "contact"];
    const observers: IntersectionObserver[] = [];

    for (const id of sections) {
      const el = document.getElementById(id);
      if (!el) continue;
      const obs = new IntersectionObserver(
        ([entry]) => {
          if (entry.isIntersecting) setActiveNav(id.toUpperCase());
        },
        { threshold: 0.4 },
      );
      obs.observe(el);
      observers.push(obs);
    }

    return () => {
      for (const o of observers) o.disconnect();
    };
  }, []);

  function scrollTo(id: string) {
    document
      .getElementById(id.toLowerCase())
      ?.scrollIntoView({ behavior: "smooth" });
    setMobileOpen(false);
  }

  return (
    <div
      className="min-h-screen"
      style={{ backgroundColor: "oklch(0.949 0.018 82)" }}
    >
      {/* ══════════════════════════════════════════════════
          TOP ACCENT STRIP
      ══════════════════════════════════════════════════ */}
      <div
        className="w-full"
        style={{ backgroundColor: "oklch(0.31 0.048 150)", height: "28px" }}
        aria-hidden="true"
      />

      {/* ══════════════════════════════════════════════════
          STICKY HEADER
      ══════════════════════════════════════════════════ */}
      <header
        className="sticky top-0 z-50 shadow-header"
        style={{
          backgroundColor: "oklch(0.957 0.016 82)",
          borderBottom: "1px solid oklch(0.845 0.013 75)",
        }}
        data-ocid="nav.panel"
      >
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4 md:px-10">
          {/* Site title - serif wordmark */}
          <button
            type="button"
            onClick={() => scrollTo("home")}
            className="cursor-pointer border-none bg-transparent p-0"
            data-ocid="nav.link"
            aria-label="Skin Blog home"
          >
            <span
              style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: "clamp(1.8rem, 3vw, 2.4rem)",
                fontWeight: 600,
                color: "oklch(0.18 0 0)",
                letterSpacing: "0.02em",
                lineHeight: 1,
              }}
            >
              Skin Blog
            </span>
          </button>

          {/* Desktop nav */}
          <nav
            className="hidden items-center gap-8 md:flex"
            aria-label="Main navigation"
          >
            {NAV_LINKS.map((link) => (
              <button
                key={link}
                type="button"
                onClick={() => scrollTo(link.toLowerCase())}
                className={[
                  "border-none bg-transparent p-0 text-xs font-medium tracking-[0.12em] uppercase cursor-pointer transition-colors duration-200",
                  activeNav === link
                    ? "text-forest underline underline-offset-4"
                    : "hover:text-forest",
                ].join(" ")}
                style={{
                  color:
                    activeNav === link
                      ? "oklch(0.31 0.048 150)"
                      : "oklch(0.18 0 0)",
                  textDecorationThickness: "1px",
                }}
                data-ocid="nav.link"
              >
                {link}
              </button>
            ))}
          </nav>

          {/* Mobile hamburger */}
          <button
            type="button"
            className="flex items-center justify-center rounded p-2 md:hidden"
            onClick={() => setMobileOpen((v) => !v)}
            aria-label="Toggle navigation"
            aria-expanded={mobileOpen}
            data-ocid="nav.toggle"
            style={{ color: "oklch(0.18 0 0)" }}
          >
            {mobileOpen ? (
              <X className="h-5 w-5" />
            ) : (
              <Menu className="h-5 w-5" />
            )}
          </button>
        </div>

        {/* Mobile nav dropdown */}
        <AnimatePresence>
          {mobileOpen && (
            <motion.nav
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.22 }}
              className="overflow-hidden border-t md:hidden"
              style={{ borderColor: "oklch(0.845 0.013 75)" }}
              aria-label="Mobile navigation"
            >
              <div className="flex flex-col gap-1 px-6 py-4">
                {NAV_LINKS.map((link) => (
                  <button
                    key={link}
                    type="button"
                    onClick={() => scrollTo(link.toLowerCase())}
                    className="border-none bg-transparent py-2.5 text-left text-sm font-medium tracking-[0.1em] uppercase cursor-pointer"
                    style={{ color: "oklch(0.18 0 0)" }}
                    data-ocid="nav.link"
                  >
                    {link}
                  </button>
                ))}
              </div>
            </motion.nav>
          )}
        </AnimatePresence>
      </header>

      <main>
        {/* ══════════════════════════════════════════════════
            HERO SECTION
        ══════════════════════════════════════════════════ */}
        <section
          id="home"
          className="relative w-full overflow-hidden"
          style={{ height: "clamp(360px, 62vh, 700px)" }}
          data-ocid="hero.section"
        >
          {/* Background photo */}
          <img
            src="/assets/generated/skinblog-hero.dim_1400x800.jpg"
            alt="Natural skincare lifestyle"
            className="h-full w-full object-cover"
            loading="eager"
          />

          {/* Left-fade gradient overlay */}
          <div
            className="absolute inset-0"
            style={{
              background:
                "linear-gradient(100deg, rgba(31,31,31,0.78) 0%, rgba(31,31,31,0.50) 40%, rgba(31,31,31,0.08) 70%, rgba(31,31,31,0) 100%)",
            }}
            aria-hidden="true"
          />

          {/* Hero copy */}
          <div className="absolute inset-0 flex items-center">
            <div className="mx-auto w-full max-w-6xl px-6 md:px-10">
              <motion.div
                initial={{ opacity: 0, y: 28 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.85, ease: "easeOut" }}
                className="max-w-lg"
              >
                <p
                  className="mb-3 text-xs font-semibold uppercase tracking-[0.22em]"
                  style={{ color: "rgba(255,255,255,0.75)" }}
                >
                  Natural Skincare Journal
                </p>
                <h1
                  className="mb-5 leading-[1.08] text-white"
                  style={{
                    fontFamily: "'Playfair Display', Georgia, serif",
                    fontSize: "clamp(2.4rem, 6vw, 4.25rem)",
                    fontWeight: 600,
                    letterSpacing: "-0.01em",
                  }}
                >
                  Nourish Your Natural Radiance.
                </h1>
                <p
                  className="mb-8 text-sm leading-relaxed"
                  style={{ color: "rgba(255,255,255,0.82)", maxWidth: "400px" }}
                >
                  Evidence-backed insights on serums, ingredients, and rituals
                  for skin that glows from within.
                </p>
                <motion.button
                  type="button"
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => scrollTo("posts")}
                  className="inline-flex items-center gap-2 rounded-[8px] px-7 py-3.5 text-xs font-semibold uppercase tracking-[0.12em] transition-opacity duration-200 hover:opacity-90"
                  style={{
                    backgroundColor: "oklch(0.929 0.022 80)",
                    color: "oklch(0.18 0 0)",
                  }}
                  data-ocid="hero.primary_button"
                >
                  Read Latest Post
                  <ChevronRight className="h-3.5 w-3.5" />
                </motion.button>
              </motion.div>
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════
            RECENT ARTICLES
        ══════════════════════════════════════════════════ */}
        <section
          id="posts"
          className="mx-auto max-w-6xl px-6 py-16 md:px-10 md:py-20"
          data-ocid="posts.section"
        >
          {/* Section heading */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="mb-12 text-center"
          >
            <h2
              className="text-3xl md:text-4xl"
              style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontWeight: 600,
                color: "oklch(0.18 0 0)",
                letterSpacing: "-0.01em",
              }}
            >
              Recent Articles
            </h2>
            <div
              className="mx-auto mt-4 h-px w-16"
              style={{ backgroundColor: "oklch(0.845 0.013 75)" }}
              aria-hidden="true"
            />
          </motion.div>

          {/* 3-column card grid */}
          <div
            className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"
            data-ocid="posts.list"
          >
            {blogPosts.map((post, i) => (
              <PostCard
                key={post.id}
                post={post}
                index={i}
                onReadMore={() => setSelectedPost(post)}
              />
            ))}
          </div>
        </section>

        {/* ══════════════════════════════════════════════════
            ABOUT SECTION
        ══════════════════════════════════════════════════ */}
        <section
          id="about"
          className="py-20"
          style={{ backgroundColor: "oklch(0.975 0.010 82)" }}
          data-ocid="about.section"
        >
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.65 }}
            className="mx-auto max-w-2xl px-6 text-center md:px-10"
          >
            <p
              className="mb-3 text-xs font-semibold uppercase tracking-[0.18em]"
              style={{ color: "oklch(0.31 0.048 150)" }}
            >
              About This Blog
            </p>
            <h2
              className="mb-6 text-3xl md:text-4xl"
              style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontWeight: 600,
                color: "oklch(0.18 0 0)",
              }}
            >
              Skincare, Backed by Science and Nature
            </h2>
            <p
              className="mb-5 text-base leading-[1.75]"
              style={{ color: "oklch(0.34 0.018 55)" }}
            >
              Skin Blog is a calm corner of the internet dedicated to
              evidence-based natural skincare. We write about ingredients,
              rituals, and routines grounded in both science and botanical
              wisdom — because the best skincare is thoughtful skincare.
            </p>
            <p
              className="text-base leading-[1.75] italic"
              style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                color: "oklch(0.47 0.048 145)",
              }}
            >
              &ldquo;Nourish slowly. Glow naturally.&rdquo;
            </p>
          </motion.div>
        </section>

        {/* ══════════════════════════════════════════════════
            CONTACT SECTION
        ══════════════════════════════════════════════════ */}
        <section
          id="contact"
          className="mx-auto max-w-xl px-6 py-20 md:px-10"
          data-ocid="contact.section"
        >
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.65 }}
            className="text-center"
          >
            <p
              className="mb-3 text-xs font-semibold uppercase tracking-[0.18em]"
              style={{ color: "oklch(0.31 0.048 150)" }}
            >
              Get in Touch
            </p>
            <h2
              className="mb-3 text-3xl md:text-4xl"
              style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontWeight: 600,
                color: "oklch(0.18 0 0)",
              }}
            >
              Say Hello
            </h2>
            <p
              className="mb-10 text-sm"
              style={{ color: "oklch(0.47 0.018 60)" }}
            >
              Have a question, story idea, or collaboration in mind? We&rsquo;d
              love to hear from you.
            </p>
          </motion.div>
          <ContactForm />
        </section>
      </main>

      {/* ══════════════════════════════════════════════════
          FOOTER
      ══════════════════════════════════════════════════ */}
      <footer
        className="w-full"
        style={{ backgroundColor: "oklch(0.31 0.048 150)" }}
        data-ocid="footer.panel"
      >
        <div className="mx-auto max-w-6xl px-6 py-12 md:px-10">
          <div className="flex flex-col items-center gap-6 md:flex-row md:justify-between">
            {/* Brand */}
            <p
              className="text-xl text-white"
              style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontWeight: 600,
                letterSpacing: "0.02em",
              }}
            >
              Skin Blog
            </p>

            {/* Footer nav */}
            <nav
              className="flex flex-wrap justify-center gap-6"
              aria-label="Footer navigation"
            >
              {NAV_LINKS.map((link) => (
                <button
                  key={link}
                  type="button"
                  onClick={() => scrollTo(link.toLowerCase())}
                  className="border-none bg-transparent text-xs font-medium uppercase tracking-[0.1em] cursor-pointer transition-colors duration-200 hover:text-white"
                  style={{ color: "rgba(255,255,255,0.65)" }}
                  data-ocid="footer.link"
                >
                  {link}
                </button>
              ))}
            </nav>

            {/* Social icons */}
            <div className="flex items-center gap-4">
              <a
                href="https://instagram.com"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Instagram"
                className="rounded-full p-1.5 transition-colors duration-200 hover:bg-white/10"
                style={{ color: "rgba(255,255,255,0.65)" }}
                data-ocid="footer.link"
              >
                <Instagram className="h-4 w-4" />
              </a>
              <a
                href="https://twitter.com"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Twitter"
                className="rounded-full p-1.5 transition-colors duration-200 hover:bg-white/10"
                style={{ color: "rgba(255,255,255,0.65)" }}
                data-ocid="footer.link"
              >
                <Twitter className="h-4 w-4" />
              </a>
              <a
                href="https://facebook.com"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Facebook"
                className="rounded-full p-1.5 transition-colors duration-200 hover:bg-white/10"
                style={{ color: "rgba(255,255,255,0.65)" }}
                data-ocid="footer.link"
              >
                <Facebook className="h-4 w-4" />
              </a>
            </div>
          </div>

          <div
            className="my-8 h-px"
            style={{ backgroundColor: "rgba(255,255,255,0.12)" }}
            aria-hidden="true"
          />

          <div className="flex flex-col items-center gap-2 text-center md:flex-row md:justify-between">
            <p className="text-xs" style={{ color: "rgba(255,255,255,0.5)" }}>
              &copy; {year} Skin Blog. All rights reserved.
            </p>
            <p className="text-xs" style={{ color: "rgba(255,255,255,0.4)" }}>
              Built with &#10084; using{" "}
              <a
                href={`https://caffeine.ai?utm_source=caffeine-footer&utm_medium=referral&utm_content=${hostname}`}
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:text-white/70 transition-colors"
              >
                caffeine.ai
              </a>
            </p>
          </div>
        </div>
      </footer>

      {/* ══════════════════════════════════════════════════
          POST MODAL
      ══════════════════════════════════════════════════ */}
      <AnimatePresence>
        {selectedPost && (
          <>
            {/* Backdrop */}
            <motion.div
              key="backdrop"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.22 }}
              className="fixed inset-0 z-[60] cursor-pointer"
              style={{
                backgroundColor: "rgba(10,10,10,0.65)",
                backdropFilter: "blur(4px)",
              }}
              onClick={() => setSelectedPost(null)}
              data-ocid="posts.modal"
              aria-hidden="true"
            />

            {/* Modal */}
            <motion.div
              key="modal"
              ref={modalRef}
              // biome-ignore lint/a11y/useSemanticElements: motion.div required for animation
              aria-modal="true"
              aria-label={selectedPost.title}
              initial={{ opacity: 0, y: 48, scale: 0.96 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 48, scale: 0.96 }}
              transition={{ duration: 0.32, ease: [0.16, 1, 0.3, 1] }}
              className="fixed inset-x-4 bottom-4 top-8 z-[70] mx-auto flex max-w-2xl flex-col overflow-hidden rounded-[10px] bg-white shadow-2xl md:inset-x-8 md:bottom-8"
              data-ocid="posts.dialog"
            >
              {/* Close button */}
              <button
                type="button"
                onClick={() => setSelectedPost(null)}
                aria-label="Close article"
                className="absolute right-4 top-4 z-10 flex h-9 w-9 items-center justify-center rounded-full transition-colors duration-200 hover:bg-black/10"
                style={{
                  color: "oklch(0.18 0 0)",
                  backgroundColor: "rgba(255,255,255,0.85)",
                }}
                data-ocid="posts.close_button"
              >
                <X className="h-4 w-4" />
              </button>

              {/* Scrollable body */}
              <div className="flex-1 overflow-y-auto">
                {/* Hero image */}
                <div
                  className="w-full overflow-hidden"
                  style={{ height: "clamp(180px, 30vw, 280px)" }}
                >
                  <img
                    src={selectedPost.imageUrl}
                    alt={selectedPost.title}
                    className="h-full w-full object-cover"
                  />
                </div>

                {/* Article content */}
                <article className="px-7 py-8 md:px-10">
                  {/* Meta */}
                  <div className="mb-4 flex flex-wrap items-center gap-3">
                    <span
                      className="rounded-full px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.1em]"
                      style={{
                        backgroundColor: "oklch(0.91 0.022 145)",
                        color: "oklch(0.31 0.048 150)",
                      }}
                    >
                      {selectedPost.category}
                    </span>
                    <span
                      className="text-[11px]"
                      style={{ color: "oklch(0.47 0.018 60)" }}
                    >
                      {selectedPost.date}
                    </span>
                  </div>

                  {/* Title */}
                  <h2
                    className="mb-6 leading-snug"
                    style={{
                      fontFamily: "'Playfair Display', Georgia, serif",
                      fontSize: "clamp(1.4rem, 3vw, 2rem)",
                      fontWeight: 600,
                      color: "oklch(0.18 0 0)",
                    }}
                  >
                    {selectedPost.title}
                  </h2>

                  <div
                    className="mb-7 h-px"
                    style={{ backgroundColor: "oklch(0.845 0.013 75)" }}
                    aria-hidden="true"
                  />

                  {/* Body paragraphs */}
                  <div className="space-y-5">
                    {selectedPost.fullContent.map((para) => (
                      <p
                        key={para.slice(0, 30)}
                        className="text-sm leading-[1.9]"
                        style={{ color: "oklch(0.28 0.010 55)" }}
                      >
                        {para}
                      </p>
                    ))}
                  </div>

                  {/* Close CTA */}
                  <div
                    className="mt-10 border-t pt-8"
                    style={{ borderColor: "oklch(0.845 0.013 75)" }}
                  >
                    <button
                      type="button"
                      onClick={() => setSelectedPost(null)}
                      className="inline-flex items-center gap-2 rounded-[8px] px-7 py-3 text-xs font-semibold uppercase tracking-[0.12em] transition-opacity duration-200 hover:opacity-85"
                      style={{
                        backgroundColor: "oklch(0.929 0.022 80)",
                        color: "oklch(0.18 0 0)",
                      }}
                      data-ocid="posts.cancel_button"
                    >
                      Close Article
                    </button>
                  </div>
                </article>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}

// ─── PostCard Component ────────────────────────────────────────────────────────
function PostCard({
  post,
  index,
  onReadMore,
}: {
  post: BlogPost;
  index: number;
  onReadMore: () => void;
}) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 32 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5, delay: index * 0.08 }}
      className="flex flex-col overflow-hidden rounded-[8px] bg-white"
      style={{
        boxShadow:
          "0 2px 16px 0 rgba(31,31,31,0.07), 0 0 0 1px rgba(216,209,199,0.6)",
      }}
      data-ocid={`posts.item.${index + 1}`}
    >
      {/* Card image */}
      <div className="overflow-hidden" style={{ height: "200px" }}>
        <img
          src={post.imageUrl}
          alt={post.title}
          className="h-full w-full object-cover transition-transform duration-500 hover:scale-105"
          loading="lazy"
        />
      </div>

      {/* Card body */}
      <div className="flex flex-1 flex-col p-5">
        {/* Date */}
        <p
          className="mb-2 text-[11px] font-medium"
          style={{ color: "oklch(0.47 0.018 60)" }}
        >
          {post.date}
        </p>

        {/* Title */}
        <h3
          className="mb-3 text-base font-semibold leading-snug"
          style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            color: "oklch(0.18 0 0)",
          }}
        >
          {post.title}
        </h3>

        {/* Excerpt */}
        <p
          className="mb-5 flex-1 text-sm leading-relaxed"
          style={{ color: "oklch(0.47 0.018 60)" }}
        >
          {post.excerpt.length > 130
            ? `${post.excerpt.slice(0, 130)}…`
            : post.excerpt}
        </p>

        {/* Read More */}
        <button
          type="button"
          onClick={onReadMore}
          className="self-start rounded-[6px] px-5 py-2.5 text-xs font-semibold uppercase tracking-[0.1em] transition-opacity duration-200 hover:opacity-85"
          style={{
            backgroundColor: "oklch(0.929 0.022 80)",
            color: "oklch(0.18 0 0)",
          }}
          data-ocid={`posts.item.${index + 1}`}
        >
          Read More
        </button>
      </div>
    </motion.article>
  );
}

// ─── ContactForm Component ─────────────────────────────────────────────────────
function ContactForm() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [status, setStatus] = useState<
    "idle" | "submitting" | "success" | "error"
  >("idle");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim() || !email.trim() || !message.trim()) return;
    setStatus("submitting");
    // Simulate submission (no backend needed for static blog)
    await new Promise((r) => setTimeout(r, 800));
    setStatus("success");
    setName("");
    setEmail("");
    setMessage("");
  }

  if (status === "success") {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="rounded-[8px] p-8 text-center"
        style={{ backgroundColor: "oklch(0.91 0.022 145)" }}
        data-ocid="contact.success_state"
      >
        <p
          className="text-sm font-medium"
          style={{ color: "oklch(0.31 0.048 150)" }}
        >
          Thank you! Your message has been received. We&rsquo;ll be in touch
          soon.
        </p>
      </motion.div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5" noValidate>
      <div>
        <label
          htmlFor="contact-name"
          className="mb-1.5 block text-xs font-semibold uppercase tracking-[0.1em]"
          style={{ color: "oklch(0.28 0.010 55)" }}
        >
          Name
        </label>
        <input
          id="contact-name"
          type="text"
          required
          autoComplete="name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Your full name"
          className="w-full rounded-[6px] border bg-white px-4 py-3 text-sm outline-none transition focus:ring-2"
          style={{
            borderColor: "oklch(0.845 0.013 75)",
            color: "oklch(0.18 0 0)",
          }}
          data-ocid="contact.input"
        />
      </div>
      <div>
        <label
          htmlFor="contact-email"
          className="mb-1.5 block text-xs font-semibold uppercase tracking-[0.1em]"
          style={{ color: "oklch(0.28 0.010 55)" }}
        >
          Email
        </label>
        <input
          id="contact-email"
          type="email"
          required
          autoComplete="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="your@email.com"
          className="w-full rounded-[6px] border bg-white px-4 py-3 text-sm outline-none transition focus:ring-2"
          style={{
            borderColor: "oklch(0.845 0.013 75)",
            color: "oklch(0.18 0 0)",
          }}
          data-ocid="contact.input"
        />
      </div>
      <div>
        <label
          htmlFor="contact-message"
          className="mb-1.5 block text-xs font-semibold uppercase tracking-[0.1em]"
          style={{ color: "oklch(0.28 0.010 55)" }}
        >
          Message
        </label>
        <textarea
          id="contact-message"
          rows={5}
          required
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          placeholder="What's on your mind?"
          className="w-full resize-none rounded-[6px] border bg-white px-4 py-3 text-sm outline-none transition focus:ring-2"
          style={{
            borderColor: "oklch(0.845 0.013 75)",
            color: "oklch(0.18 0 0)",
          }}
          data-ocid="contact.textarea"
        />
      </div>

      {status === "error" && (
        <p
          className="text-xs"
          style={{ color: "oklch(0.577 0.245 27.325)" }}
          data-ocid="contact.error_state"
        >
          Something went wrong. Please try again.
        </p>
      )}

      <button
        type="submit"
        disabled={status === "submitting"}
        className="w-full rounded-[8px] py-3.5 text-sm font-semibold uppercase tracking-[0.12em] text-white transition-opacity duration-200 hover:opacity-85 disabled:opacity-60"
        style={{ backgroundColor: "oklch(0.34 0.045 150)" }}
        data-ocid="contact.submit_button"
      >
        {status === "submitting" ? "Sending…" : "Send Message"}
      </button>
    </form>
  );
}
